/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRG_Assignment;
import static PRG_Assignment.Quotation.FinalTotal0;
import static PRG_Assignment.Quotation.ReceiptItem;
import static PRG_Assignment.Quotation.ReceiptPrice;
import static PRG_Assignment.Quotation.ReceiptQuantity;
import java.util.Date;
import java.text.SimpleDateFormat;
import static PRG_Assignment.Cashiers.CurrentTeller;
import java.text.DecimalFormat;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;
/**
 *
 * @author Ruaan Cloete
 */
public class Receipt extends javax.swing.JFrame {
public double Paid =0;
    
    public Receipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        BackButton1 = new javax.swing.JButton();
        PRButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EnterAmountPaidTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LTPButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        BackButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BackButton1.setText("Back");
        BackButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BackButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton1ActionPerformed(evt);
            }
        });

        PRButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        PRButton2.setText("Print Receipt");
        PRButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PRButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Amount Paid");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EnterAmountPaidTextField1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        EnterAmountPaidTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LTPButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LTPButton3.setText("Load Total Price");
        LTPButton3.setActionCommand("");
        LTPButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LTPButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LTPButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(82, 82, 82)
                                .addComponent(EnterAmountPaidTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LTPButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PRButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BackButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTPButton3)
                    .addComponent(PRButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(EnterAmountPaidTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BackButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PRButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRButton2ActionPerformed
        DecimalFormat df = new DecimalFormat("0.00");
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Paid=Double.parseDouble(EnterAmountPaidTextField1.getText());
        double Total;
        double FinalTotal=0;
        jTextArea1.setText("\t\tHubbly Bubbly Paradise\t\t\n");
        jTextArea1.append("\n");
        jTextArea1.append("\t\tThe home of all your hubbly needs\t\t\n");
        jTextArea1.append("\n");
        jTextArea1.append("\n");
        jTextArea1.append("Name\tQTY\tPrice\tTotal\n");
        int max =ReceiptItem.size();
        for(int c=0;c<max;c++){
        Total = (ReceiptQuantity.get(c))*(ReceiptPrice.get(c));
        FinalTotal=FinalTotal+Total;
        jTextArea1.append(ReceiptItem.get(c)+"\t"+ReceiptQuantity.get(c)+"\t"+ReceiptPrice.get(c)+"\t"+Total+"\n");
        jTextArea1.append("\n");
        }
        jTextArea1.append("\n");
        jTextArea1.append("\n");
        jTextArea1.append("VAT@15%\t\t\t"+((FinalTotal)*0.15)+"\n");
        String VAT = df.format(FinalTotal-((FinalTotal)*0.15));
        jTextArea1.append("Total\t\t\t"+VAT+"\n");
        jTextArea1.append("Tendered\t\t\t"+Paid+"\n");
        if(Paid>((FinalTotal-((FinalTotal)*0.15)))){
        String change = df.format(Paid-(FinalTotal+((FinalTotal)*0.15)));
        jTextArea1.append("Change\t\t\t"+(Paid-(FinalTotal+((FinalTotal)*0.15)))+"\n");
        double Change = (Paid-(FinalTotal+((FinalTotal)*0.15)));
        jTextArea1.append("\n");
        jTextArea1.append("\n");
        jTextArea1.append("Date:\t"+(dateFormat.format(date))+"\n");
        jTextArea1.append("Cashier:\t"+CurrentTeller+"\n");
        jTextArea1.append("\n");
        jTextArea1.append("\tThank You For Your Support\n");
        jTextArea1.append("\tPlease Return Soon");
        jTextArea1.append("\n");
    
    int d = (int)Change;
    int twohundreds = d/200;
    int d200 = d%200; 
    int hundreds = d200/100;
    int d100 = d%100;
    int fifties = d100/50;
    int d50 = d%50;
    int twenties = d/20;
    int d20 = d%20;
    int tens = d20/10;
    int d10 = d%10;
    int fives = d10/5;
    int d5 = d%5;
    int ones = d5;
    
    String mostr = df.format(Change);
    String changeString = Double.toString(Change);
    String[] parts = mostr.split("\\.");
    String part2 = parts[1];
    double cents = Double.parseDouble(part2);
    
    int centsb = (int)cents;
    int fiftyc = centsb / 50;
    int cents1 = centsb % 50;
    int tenc = cents1 / 10;
    int cents2 = centsb % 10;
    int fivec = cents2 / 5;
    int cents3 = centsb % 5;
    jTextArea1.append("Your change is disbursed as follows:");
    if(twohundreds>0){
        jTextArea1.append(" N$200 X "+twohundreds+",");
    }if(hundreds>0){
        jTextArea1.append(" N$100 X "+hundreds+",");
    }if(fifties>0){
        jTextArea1.append(" N$50 X "+fifties+",");
    }if(twenties>0){
        jTextArea1.append(" N$20 X "+twenties+",");
    }if(tens>0){
        jTextArea1.append(" N$10 X "+tens+",");
    }if(fives>0){
        jTextArea1.append(" N$5 X "+fives+",");
    }if(ones>0){
        jTextArea1.append(" N$1 X "+ones+",");
    }if(fiftyc>0){
        jTextArea1.append(" 50c X "+fiftyc+",");
    }if(tenc>0){
        jTextArea1.append(" 10c X "+tenc+",");
    }if(fivec>0){
        jTextArea1.append(" 5c X "+fivec+"\n");
    }
    }else{
        showMessageDialog(null, "Insufficient funds", "Error", ERROR_MESSAGE);
        jTextArea1.setText("Insufficient funds");
    }
    }//GEN-LAST:event_PRButton2ActionPerformed

    private void BackButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton1ActionPerformed
        setVisible(false);
        new CashiersPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButton1ActionPerformed

    private void LTPButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LTPButton3ActionPerformed
       String N = Double.toString((FinalTotal0*0.15)+FinalTotal0);
        jTextArea1.setText(N);
    }//GEN-LAST:event_LTPButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton1;
    private javax.swing.JTextField EnterAmountPaidTextField1;
    private javax.swing.JButton LTPButton3;
    private javax.swing.JButton PRButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
